# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setWindowModality(QtCore.Qt.NonModal)
        MainWindow.resize(800, 612)
        MainWindow.setToolButtonStyle(QtCore.Qt.ToolButtonIconOnly)
        MainWindow.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(10, 10, 75, 23))
        self.pushButton.setObjectName("pushButton")
        self.gridLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(510, 30, 261, 471))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout1 = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout1.setContentsMargins(0, 0, 0, 0)
        self.gridLayout1.setObjectName("gridLayout1")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 23))
        self.menubar.setObjectName("menubar")
        self.menu_F = QtWidgets.QMenu(self.menubar)
        self.menu_F.setObjectName("menu_F")
        self.menuSet = QtWidgets.QMenu(self.menu_F)
        self.menuSet.setObjectName("menuSet")
        self.menu = QtWidgets.QMenu(self.menubar)
        self.menu.setToolTipsVisible(True)
        self.menu.setObjectName("menu")
        MainWindow.setMenuBar(self.menubar)
        self.toolBar = QtWidgets.QToolBar(MainWindow)
        self.toolBar.setMovable(False)
        self.toolBar.setObjectName("toolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.statusBar = QtWidgets.QStatusBar(MainWindow)
        self.statusBar.setObjectName("statusBar")
        MainWindow.setStatusBar(self.statusBar)
        self.actionopen = QtWidgets.QAction(MainWindow)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("Anki_2_32px_1183825_easyicon.net.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionopen.setIcon(icon)
        self.actionopen.setObjectName("actionopen")
        self.actionclose = QtWidgets.QAction(MainWindow)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("2_direction_folded_32px_1184147_easyicon.net.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionclose.setIcon(icon1)
        self.actionclose.setObjectName("actionclose")
        self.actionPage1 = QtWidgets.QAction(MainWindow)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("setting_2_folded_32px_1184225_easyicon.net.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionPage1.setIcon(icon2)
        self.actionPage1.setObjectName("actionPage1")
        self.actionPage2 = QtWidgets.QAction(MainWindow)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("flag_2_folded_32px_1184183_easyicon.net.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionPage2.setIcon(icon3)
        self.actionPage2.setObjectName("actionPage2")
        self.actionSystemInfo = QtWidgets.QAction(MainWindow)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("1Password_32px_1183799_easyicon.net.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionSystemInfo.setIcon(icon4)
        self.actionSystemInfo.setObjectName("actionSystemInfo")
        self.actionexit = QtWidgets.QAction(MainWindow)
        self.actionexit.setObjectName("actionexit")
        self.menuSet.addAction(self.actionPage1)
        self.menuSet.addAction(self.actionPage2)
        self.menu_F.addAction(self.actionopen)
        self.menu_F.addAction(self.actionclose)
        self.menu_F.addSeparator()
        self.menu_F.addAction(self.menuSet.menuAction())
        self.menu_F.addAction(self.actionexit)
        self.menu.addSeparator()
        self.menu.addAction(self.actionSystemInfo)
        self.menu.addSeparator()
        self.menubar.addAction(self.menu_F.menuAction())
        self.menubar.addAction(self.menu.menuAction())
        self.toolBar.addAction(self.actionopen)
        self.toolBar.addAction(self.actionclose)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionPage1)
        self.toolBar.addAction(self.actionPage2)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionSystemInfo)

        self.retranslateUi(MainWindow)
        self.actionexit.triggered.connect(MainWindow.close)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "主窗口测试"))
        self.pushButton.setText(_translate("MainWindow", "测试按钮"))
        self.menu_F.setTitle(_translate("MainWindow", "文件(&F)"))
        self.menuSet.setTitle(_translate("MainWindow", "显示提示框"))
        self.menu.setTitle(_translate("MainWindow", "系统信息(&I)"))
        self.toolBar.setWindowTitle(_translate("MainWindow", "toolBar"))
        self.actionopen.setText(_translate("MainWindow", "打开界面1"))
        self.actionopen.setIconText(_translate("MainWindow", "打开界面1"))
        self.actionopen.setToolTip(_translate("MainWindow", "打开测试界面1"))
        self.actionopen.setStatusTip(_translate("MainWindow", "打开界面为测试界面1"))
        self.actionopen.setShortcut(_translate("MainWindow", "Alt+O"))
        self.actionclose.setText(_translate("MainWindow", "隐藏界面1"))
        self.actionclose.setToolTip(_translate("MainWindow", "隐藏测试界面1"))
        self.actionclose.setStatusTip(_translate("MainWindow", "隐藏测试界面1"))
        self.actionclose.setShortcut(_translate("MainWindow", "Alt+C"))
        self.actionPage1.setText(_translate("MainWindow", "提示信息框"))
        self.actionPage1.setIconText(_translate("MainWindow", "弹出提示信息框"))
        self.actionPage1.setToolTip(_translate("MainWindow", "提示信息框已弹出"))
        self.actionPage1.setStatusTip(_translate("MainWindow", "弹出提示信息框"))
        self.actionPage2.setText(_translate("MainWindow", "输入信息框"))
        self.actionPage2.setIconText(_translate("MainWindow", "弹出输入信息框"))
        self.actionPage2.setToolTip(_translate("MainWindow", "请输入数值"))
        self.actionPage2.setStatusTip(_translate("MainWindow", "弹出输入信息框"))
        self.actionSystemInfo.setText(_translate("MainWindow", "系统信息"))
        self.actionexit.setText(_translate("MainWindow", "退出"))

